@host=https://localhost:7252
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyODk2NmY3MC03OGI0LTQxNjQtYTk1ZS1lYjVjOGMxZTdmYTYiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6ImM4Y2RiZWEwLTBmYjUtNDc5Mi05OGQzLTkzODc0YzcwNTRkMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE2NzkxNjcxOTAsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.2Y5Ycc-F-Xr_tjs30HXNH2yd4_P421kz2vTNxefF400

POST {{host}}/api/v1/coaches
Content-Type: application/json
Authorization: bearer {{token}}

{
    "userId": "28966f70-78b4-4164-a95e-eb5c8c1e7fa6"
}