@host=http://localhost:5193
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGU5MThiYS0xOGM5LTQ0YzgtYjhjNC05MDUxMzQwZWM0NWIiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6ImUwYjZhNTYzLWU0ZmUtNDlkMy05ZGU2LWMzYmMxYWIxODdmNCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE2Nzc5NjAyNDgsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.VjaFGD9FUI9EXGxGU5eoYkh2-qq4UUh4vavqoy_YeSw

POST {{host}}/api/v1/coaches
Content-Type: application/json
Authorization: bearer {{token}}

{
    "userId": "f4e918ba-18c9-44c8-b8c4-9051340ec45b"
}