@host=http://localhost:8001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMjUxNDQ0MC0yZTBmLTQwZTQtYjJmNC05MmM4NTEyZDYzNDciLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6ImQyM2NjOGIzLWMyNGQtNDJmZS05ZGZhLTI0NDBmMDYyMjY1MiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE2ODMyMzU0MTMsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.IBE12yzOjGMq5q75h0-HckI9GznLUH83vqbgYRIh5xk

POST {{host}}/api/v1/coaches
Content-Type: application/json
Authorization: bearer {{token}}

{
    "userId": "e2514440-2e0f-40e4-b2f4-92c8512d6347"
}