@host=https://localhost:7252
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Y2RjMWZkYy1hZTAwLTQxZTItYjQ2Ni1mNDFlNTNjMjU1ZDkiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjgyZDc4ZTY1LTU3NzAtNDFlYy04MDBmLTk5NTE4ZWQ0MzljYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2Nzg4OTgwNjIsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.SB9TnQ-Y0Q-BuZwufSZoi44FkAMtEzofp5mVxpa2Yig
@coachId=700bca96-d817-46f3-9ab1-7da4a3173483

GET  {{host}}/api/v1/coaches/{{coachId}}
Content-Type: application/json
Authorization: bearer {{token}}