@host=http://localhost:8001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NzQwMzFiYi0xYWZmLTRhZjUtODEzYy0wNGQzNjFiNjE4NDgiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6ImVkMDUzOGRmLTFiMzAtNGJhYS1hZmQ1LTAyMzRhYjEwZGI1OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQ29hY2giLCJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTY4MjUxMTA0NSwiaXNzIjoiU3BhcnRhbkZpdG5lc3MiLCJhdWQiOiJTcGFydGFuRml0bmVzcyJ9.gUuRgV0_eVGyqpaXb79bkLFciLcat_S8WEwJriH9Hps

GET {{host}}/api/v1/exercises?p=1&s=name&o=desc&q=supine
Content-Type: application/json
Authorization: bearer {{token}}