@host=http://localhost:8001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NzQwMzFiYi0xYWZmLTRhZjUtODEzYy0wNGQzNjFiNjE4NDgiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjFkNzc1MWZmLTkzOTQtNDkwMi05MmI5LTY5MTQ3NWE1MzAxOCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQ29hY2giLCJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTY4MjI2ODkwNSwiaXNzIjoiU3BhcnRhbkZpdG5lc3MiLCJhdWQiOiJTcGFydGFuRml0bmVzcyJ9.tA_uDaAvKcPxNa-tPM0ZwXzOf6EDXUkHF_cWP_FKigw

GET {{host}}/api/v1/exercises?page=1&size=4
Content-Type: application/json
Authorization: bearer {{token}}