@host=http://localhost:8001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMjUxNDQ0MC0yZTBmLTQwZTQtYjJmNC05MmM4NTEyZDYzNDciLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjI3ZTgzYThiLWUwY2MtNDk2OS05OTIzLWVmY2IxZmQ0NDcyMyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQ29hY2giLCJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTY4MzQ4NzUyMywiaXNzIjoiU3BhcnRhbkZpdG5lc3MiLCJhdWQiOiJTcGFydGFuRml0bmVzcyJ9.R1byNenYA97RKTIH7pnS0-tmTLjb-IDZxXZy_fxLZ4w

GET {{host}}/api/v1/muscle-groups?id=75156fb6-75b6-46d5-9776-20b246f2dc5a
Content-Type: application/json
Authorization: bearer {{token}}