@host=http://localhost:8001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMjUxNDQ0MC0yZTBmLTQwZTQtYjJmNC05MmM4NTEyZDYzNDciLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjA3NmYzM2ZiLTk4MDktNGZlMy05ZGMyLTRkNzk1OGM5MjFmMyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQ29hY2giLCJBZG1pbmlzdHJhdG9yIl0sIlVzZXJJZCI6ImUyNTE0NDQwLTJlMGYtNDBlNC1iMmY0LTkyYzg1MTJkNjM0NyIsIkNvYWNoSWQiOiI0YzQ1Njc1Yy1kY2JhLTRjNDMtYjZmYi1hNzk3NTYwMWM3MTkiLCJBZG1pbmlzdHJhdG9ySWQiOiIwNWZmNTBlNS0zMWNkLTRlNjUtOTM0ZC03ZDAwMjRhMjZmOWEiLCJleHAiOjE2ODQ1MjcxOTAsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.MQF-ALxxiAq-z9eQ7VerZ3b3Ryiu54hZND1pGl1iWBI
@muscleGroupId=d254c751-0a42-42af-94cd-553bb8ef14a8

GET {{host}}/api/v1/muscle-groups/{{muscleGroupId}}
Content-Type: application/json
Authorization: bearer {{token}}