@host=https://localhost:7252
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Y2RjMWZkYy1hZTAwLTQxZTItYjQ2Ni1mNDFlNTNjMjU1ZDkiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjA3ZTNjMzc1LWJiOTctNDI0NC04YTQ5LWNmMzM2ODdiYjE0OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2Nzg4OTk2MDYsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.zLLFYg0XJFkl14ovbOIElRQgtFM9m_IifO9QNqO7Zgo
@muscleGroupId=44761242-6d79-48da-8131-4d5897d7e894

GET {{host}}/api/v1/muscle-groups/{{muscleGroupId}}
Content-Type: application/json
Authorization: bearer {{token}}