@host=http://localhost:5193
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OGVlMzZmOC02YmRkLTQyNWQtYWVhYy04ZTAzOThlZGQ0Y2MiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjYwZTFhNjcwLTE5NmQtNGI3ZC04NzNlLWFhMDUyYjg5YzFlNCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE2NzgzMDUxNzIsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.FFBZUtzV4xl6AstyXsodyCVL89QKUad90RCs_a8MfJY

POST {{host}}/api/v1/admins
Content-Type: application/json
Authorization: bearer {{token}}

{
    "userId": "78ee36f8-6bdd-425d-aeac-8e0398edd4cc"
}