@host=http://localhost:5193
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Y2RjMWZkYy1hZTAwLTQxZTItYjQ2Ni1mNDFlNTNjMjU1ZDkiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6ImZjMzExMTlkLTFiMDYtNGZjOS1iMGJlLTIxODIzNTk2YzUwMiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE2Nzg4OTU5NDEsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.l2BrGWwxSBk1tBHhHocr-99t2NLYqL6g8qo2cExNS8o

POST {{host}}/api/v1/admins
Content-Type: application/json
Authorization: bearer {{token}}

{
    "userId": "6cdc1fdc-ae00-41e2-b466-f41e53c255d9"
}