@host=http://localhost:5193
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Y2RjMWZkYy1hZTAwLTQxZTItYjQ2Ni1mNDFlNTNjMjU1ZDkiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjlhY2Q3NDJhLWJiMTAtNDEwNC1hNjY5LTI5YTZjZjM4ZDNkNCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2Nzg4OTYwNzAsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.IukGTW78nb4oVtt4s3soRvjExqPlaCKTVUOetzeIw50
@adminId=6152a7b3-4856-4be9-b028-0b49253c48b1

GET {{host}}/api/v1/admins/{{adminId}}
Content-Type: application/json
Authorization: bearer {{token}}