@host=http://localhost:8001

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Jamey",
    "lastName": "Schaap",
    "profileImage": "https://picsum.photos/200",
    "email": "test@spartanfitness.com",
    "password": "jamey123!"
}