@host=http://localhost:5193

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Jamey",
    "lastName": "Schaap",
    "profileImage": "https://google.com",
    "email": "jameyschaap1@spartanfitness.com",
    "password": "jamey123!"
}