@host=http://localhost:8001/api/v1

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Jamey",
    "lastName": "Schaap",
    "profileImage": "https://picsum.photos/200",
    "email": "jameyschaap32@gmail.com",
    "password": "jamey123!"
}