@host=http://localhost:8001
@userId=78ee36f8-6bdd-425d-aeac-8e0398edd4cc
@coachApplicationId=3ef157dd-781b-4657-809e-49ae70cfc3f6
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OGVlMzZmOC02YmRkLTQyNWQtYWVhYy04ZTAzOThlZGQ0Y2MiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjQ5ODk1MWJlLTU0MjYtNDFhZC1hMTc3LTQ2MTI0MGI3NGU4YSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NzgzMDU4MTAsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.HGBIKSoK79vtLQb4VTzJF5lyyAR0JNsvdLsXFlZrcFw

PUT {{host}}/api/v1/users/{{userId}}/coach-applications/{{coachApplicationId}}/approve
Content-Type: application/json
Authorization: bearer {{token}}

{
    "remarks": "Looks good!"
}