@host=http://localhost:8001
@userId=c7d02b9d-0331-40e2-b4c4-985eff2d63a0
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjN2QwMmI5ZC0wMzMxLTQwZTItYjRjNC05ODVlZmYyZDYzYTAiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjY5OWY2YjVlLTBiNzctNDJmYS1iODdiLTFjOTUyMTYxZmI2OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE2NzgzOTQ1NzAsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.L5et31oTaXIXx6_TpGMmhlQYU3pO5cFvuhSn6h3I7QI

POST {{host}}/api/v1/users/{{userId}}/coach-applications/apply
Content-Type: application/json
Authorization: bearer {{token}}

{
    "motivation": "I have 7 years of experience in bodybuilding."
}