@host=http://localhost:8001
@userId=c7d02b9d-0331-40e2-b4c4-985eff2d63a0
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YTAwZjAxZS1kZWUwLTQzNDgtYmUyMy05ZGU3ODhhNmFhOTAiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjkwZDE2ODdhLWQyZGItNGI2Ni1hYzIzLTU2YjA3YTBmNjIzNiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE2NzgzOTQ4OTYsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ.x_jqaruE6SAcSYk7etrsR8HNM8TM68clldicOWIbu7w
@coachApplicationId=dc5b3813-3f15-406f-9c5a-2fb68933232c

GET {{host}}/api/v1/users/{{userId}}/coach-applications/{{coachApplicationId}}
Content-Type: application/json
Authorization: bearer {{token}}
