@host=http://localhost:5193
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyODk2NmY3MC03OGI0LTQxNjQtYTk1ZS1lYjVjOGMxZTdmYTYiLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6IjAxOTBmMDkwLTU5Y2YtNDUyNy04YTIyLTlkMTdmZTMwNDkwYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQ29hY2giXSwiZXhwIjoxNjc5MTY3MjI4LCJpc3MiOiJTcGFydGFuRml0bmVzcyIsImF1ZCI6IlNwYXJ0YW5GaXRuZXNzIn0.eTSJNbDqsTQz3SSJRCo0NEcRepswShKsxQ5oKUC0ctc
@coachId=26081544-1d9f-4297-a297-fa87232c5155

### Create without exercises
POST {{host}}/api/v1/coaches/{{coachId}}/workouts/create
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name": "Pull",
    "description": "Back, bicep and read delt workout",
    "image": "https://google.com"
}

### Create with exercises
POST {{host}}/api/v1/coaches/{{coachId}}/workouts/create
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name": "Push",
    "description": "Chest, shoulder and tricep workout",
    "image": "https://google.com",
    "workoutExercises": [
        {
            "exerciseId": "afd93519-4e8a-4d46-bf56-5f164907044b",
            "orderNumber": "1",
            "sets": "3",
            "minReps": "8",
            "maxReps": "10",
            "exerciseType": "Default"
        },
          {
            "exerciseId": "b7bb2b57-bb25-4472-a594-d2288331f8e9",
            "orderNumber": "2",
            "sets": "2",
            "minReps": "8",
            "maxReps": "8",
            "exerciseType": "Default"
        }
    ]
}