@host=http://localhost:8001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMjUxNDQ0MC0yZTBmLTQwZTQtYjJmNC05MmM4NTEyZDYzNDciLCJnaXZlbl9uYW1lIjoiSmFtZXkiLCJmYW1pbHlfbmFtZSI6IlNjaGFhcCIsImp0aSI6ImEzZmZmNzMwLTA0ZDYtNDIxYS04NjAyLTlkMGJiYmM2MzkwMyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQ29hY2giLCJBZG1pbmlzdHJhdG9yIl0sIlVzZXJJZCI6ImUyNTE0NDQwLTJlMGYtNDBlNC1iMmY0LTkyYzg1MTJkNjM0NyIsIkNvYWNoSWQiOiI0YzQ1Njc1Yy1kY2JhLTRjNDMtYjZmYi1hNzk3NTYwMWM3MTkiLCJBZG1pbmlzdHJhdG9ySWQiOiIwNWZmNTBlNS0zMWNkLTRlNjUtOTM0ZC03ZDAwMjRhMjZmOWEiLCJleHAiOjE2OTA0NTY2OTgsImlzcyI6IlNwYXJ0YW5GaXRuZXNzIiwiYXVkIjoiU3BhcnRhbkZpdG5lc3MifQ._dX1GhxrqFb0J6-HAvemckXgEN1pIA0qvK2J6nkdIH4
@coachId=4c45675c-dcba-4c43-b6fb-a7975601c719
@workoutId=17f1d4af-1110-4a07-ba14-580bc32c6dbf

### Create without exercises
DELETE  {{host}}/api/v1/coaches/{{coachId}}/workouts/{{workoutId}}/delete
Content-Type: application/json
Authorization: bearer {{token}}