apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: spartanfitness
    tier: database
spec:
  type: ClusterIP
  selector:
    app: spartanfitness
    tier: database
  ports:
    - port: 1433
      targetPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: spartanfitness
      tier: database
  template:
    metadata:
      labels:
        app: spartanfitness
        tier: database
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-sa-password
                  key: SA_PASSWORD
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 1433
  replicas: 1
