apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: githubfitness
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: githubfitness
    tier: frontend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: githubfitness
      tier: frontend
  template:
    metadata:
      labels:
        app: githubfitness
        tier: frontend
    spec:
      containers:
        - name: vite-react
          image: jamey010/githubfitness:frontend-latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
              name: frontend-secrets
          ports:
            - containerPort: 8000
  replicas: 1